// saga
export const SWITCH_ASIDE_SAGA = 'SWITCH_ASIDE_SAGA'
export const SWITCH_NORMAL_LIGHTS_SAGA = 'SWITCH_NORMAL_LIGHTS_SAGA'
export const SWITCH_LONG_LIGHTS_SAGA = 'SWITCH_LONG_LIGHTS_SAGA'
export const UPDATE_GENERAL_SETTINGS_SAGA = 'UPDATE_GENERAL_SETTINGS_SAGA'
export const CATCH_MOVEMENT_SAGA = 'CATCH_MOVEMENT_SAGA'
// redux
export const SWITCH_ASIDE = 'SWITCH_ASIDE'
export const SWITCH_NORMAL_LIGHTS = 'SWITCH_NORMAL_LIGHTS'
export const SWITCH_LONG_LIGHTS = 'SWITCH_LONG_LIGHTS'
export const UPDATE_GENERAL_SETTINGS = 'UPDATE_GENERAL_SETTINGS'
export const CATCH_MOVEMENT = 'CATCH_MOVEMENT'
